version: "3.5"

# ---
# Check docker-compose.dev.yml and docker-compose.prod.yml for instructions on
# how to get the services running...
# ---

services:

  # Django
  web:
    container_name: sb_web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    restart: on-failure
    environment:
      SB_DB_HOST: database
      SB_DB_NAME: "secretboard"
      SB_DB_USER: "secretboard"
      SB_SECRET_KEY: ${SB_SECRET_KEY}
    depends_on:
      - database

  # Postgres Database
  database:
      container_name: sb_database
      image: postgres:alpine
      restart: on-failure
      environment:
        POSTGRES_USER: "secretboard"
