version: "3.5"
networks:
  default:
    external:
      name: gateway

services:
  db:
    image: postgres:alpine
    restart: on-failure
    environment:
      POSTGRES_USER: "secretboard"
      POSTGRES_PASSWORD: ${SB_DB_PASSWORD}
    labels:
      - traefik.enable=false

  web:
    image: secretboard/web
    command: ../docker/web/wait-for-it.sh -t 5 db:5432 -- sh -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 -w 4 secretboard.wsgi"
    restart: on-failure
    environment:
      SB_SECRET_KEY: ${SB_SECRET_KEY}
      SB_DB_HOST: db
      SB_DB_NAME: "secretboard"
      SB_DB_USER: "secretboard"
      SB_DB_PASSWORD: ${SB_DB_PASSWORD}
    volumes:
      - static_files:/static_files
    depends_on:
      - db
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false

  nginx:
    image: secretboard/nginx
    restart: on-failure
    volumes:
      - static_files:/static_files
    depends_on:
      - web
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.frontend.rule=Host:secretboard.org,www.secretboard.org
      - traefik.frontend.headers.SSLHost=www.secretboard.org
      - traefik.frontend.redirect.regex=^https?://secretboard.org/(.*)
      - traefik.frontend.redirect.replacement=https://www.secretboard.org/$${1}

volumes:
  static_files:
